# ELI5 Article Tags

# --- !Ups
ALTER TABLE Articles ADD COLUMN tags CHARACTER VARYING NOT NULL DEFAULT '';
ALTER TABLE Articles ADD COLUMN recap CHARACTER VARYING NOT NULL DEFAULT '';

# --- !Downs
ALTER TABLE Articles DROP COLUMN recap;
ALTER TABLE Articles DROP COLUMN tags;
